#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SecureFileTransfer.Resource", IsApplication=true)]

namespace SecureFileTransfer
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::SecureFileTransfer.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::SecureFileTransfer.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::SecureFileTransfer.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000b
			public const int AbortButton = 2131034123;
			
			// aapt resource value: 0x7f050011
			public const int ConnectManuallyButton = 2131034129;
			
			// aapt resource value: 0x7f050000
			public const int ConnectedToField = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int CurrentTransferFileNameField = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int CurrentTransferLayout = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int CurrentTransferProgressBar = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int CurrentTransferStatus = 2131034122;
			
			// aapt resource value: 0x7f050007
			public const int CurrentTransferTitleLabel = 2131034119;
			
			// aapt resource value: 0x7f05000c
			public const int DisconnectButton = 2131034124;
			
			// aapt resource value: 0x7f050014
			public const int FileNameLabel = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int ProgressBar = 2131034133;
			
			// aapt resource value: 0x7f050010
			public const int QRContainer = 2131034128;
			
			// aapt resource value: 0x7f05000d
			public const int ReceiveFilesButton = 2131034125;
			
			// aapt resource value: 0x7f050002
			public const int SendContactsButton = 2131034114;
			
			// aapt resource value: 0x7f05000e
			public const int SendFilesButton = 2131034126;
			
			// aapt resource value: 0x7f050003
			public const int SendOtherButton = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int SendPicturesButton = 2131034113;
			
			// aapt resource value: 0x7f050016
			public const int StatusLabel = 2131034134;
			
			// aapt resource value: 0x7f050012
			public const int TransfersListView = 2131034130;
			
			// aapt resource value: 0x7f050017
			public const int contentFrame = 2131034135;
			
			// aapt resource value: 0x7f050013
			public const int imageView1 = 2131034131;
			
			// aapt resource value: 0x7f050004
			public const int linearLayout1 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int linearLayout2 = 2131034117;
			
			// aapt resource value: 0x7f05000f
			public const int textView1 = 2131034127;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ClientActivity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ServerActivity = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ServerConnectedActivity = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int TransferListCompletedItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int TransferListItem = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int zxingscanneractivitylayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int zxingscannerfragmentlayout = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040011
			public const int Abort = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int AbortAll = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int AbortAreYouSure = 2130968595;
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f04000c
			public const int ClientSendContacts = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int ClientSendOther = 2130968589;
			
			// aapt resource value: 0x7f04000b
			public const int ClientSendPictures = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int ConnectedToFormatStr = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int Connecting = 2130968585;
			
			// aapt resource value: 0x7f04000f
			public const int CurrentFileTransferRemainingFormatStr = 2130968591;
			
			// aapt resource value: 0x7f040008
			public const int Disconnect = 2130968584;
			
			// aapt resource value: 0x7f04000e
			public const int IncomingFileTransfers = 2130968590;
			
			// aapt resource value: 0x7f040015
			public const int No = 2130968597;
			
			// aapt resource value: 0x7f040005
			public const int QRCodeInvalid = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int QRCodeInvalidTitle = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int ReceiveFiles = 2130968582;
			
			// aapt resource value: 0x7f040010
			public const int SelectPictures = 2130968592;
			
			// aapt resource value: 0x7f040007
			public const int SendFiles = 2130968583;
			
			// aapt resource value: 0x7f040002
			public const int ServerConnectManually = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int ServerConnectManuallyInfoFormatStr = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int ServerQRCodeInformation = 2130968577;
			
			// aapt resource value: 0x7f040014
			public const int Yes = 2130968596;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
