#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SecureFileTransfer.Resource", IsApplication=true)]

namespace SecureFileTransfer
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::SecureFileTransfer.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::SecureFileTransfer.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::SecureFileTransfer.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int plain_button_background_normal = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int plain_button_background_pressed = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int scanner_overlay_text_background = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int text_color = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int text_shadow_color = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int plain_button_corner_radius = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bkg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int plain_button_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int plain_button_background_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int plain_button_background_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int wlan_anim = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int wlan_anim_1 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int wlan_anim_2 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int wlan_anim_3 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int wlan_anim_4 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int wlan_anim_5 = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09000a
			public const int AbortButton = 2131296266;
			
			// aapt resource value: 0x7f090013
			public const int CheckBox = 2131296275;
			
			// aapt resource value: 0x7f09001a
			public const int ConnectManuallyButton = 2131296282;
			
			// aapt resource value: 0x7f090000
			public const int ConnectedToField = 2131296256;
			
			// aapt resource value: 0x7f090015
			public const int ContactName = 2131296277;
			
			// aapt resource value: 0x7f090014
			public const int ContactPhoto = 2131296276;
			
			// aapt resource value: 0x7f090007
			public const int CurrentTransferFileNameField = 2131296263;
			
			// aapt resource value: 0x7f090005
			public const int CurrentTransferLayout = 2131296261;
			
			// aapt resource value: 0x7f090008
			public const int CurrentTransferProgressBar = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int CurrentTransferStatus = 2131296265;
			
			// aapt resource value: 0x7f090006
			public const int CurrentTransferTitleLabel = 2131296262;
			
			// aapt resource value: 0x7f09000b
			public const int DisconnectButton = 2131296267;
			
			// aapt resource value: 0x7f09001d
			public const int FileNameLabel = 2131296285;
			
			// aapt resource value: 0x7f090010
			public const int IPAddressField = 2131296272;
			
			// aapt resource value: 0x7f09000c
			public const int ImageView = 2131296268;
			
			// aapt resource value: 0x7f090016
			public const int ListView = 2131296278;
			
			// aapt resource value: 0x7f090012
			public const int PasswordField = 2131296274;
			
			// aapt resource value: 0x7f09001e
			public const int ProgressBar = 2131296286;
			
			// aapt resource value: 0x7f090019
			public const int QRContainerView = 2131296281;
			
			// aapt resource value: 0x7f090017
			public const int ScanCodeButton = 2131296279;
			
			// aapt resource value: 0x7f090021
			public const int Send = 2131296289;
			
			// aapt resource value: 0x7f090002
			public const int SendContactsButton = 2131296258;
			
			// aapt resource value: 0x7f090001
			public const int SendPicturesButton = 2131296257;
			
			// aapt resource value: 0x7f09001f
			public const int StatusLabel = 2131296287;
			
			// aapt resource value: 0x7f09000d
			public const int TextView = 2131296269;
			
			// aapt resource value: 0x7f09001b
			public const int TransfersListView = 2131296283;
			
			// aapt resource value: 0x7f090020
			public const int contentFrame = 2131296288;
			
			// aapt resource value: 0x7f09001c
			public const int imageView1 = 2131296284;
			
			// aapt resource value: 0x7f090003
			public const int linearLayout1 = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int linearLayout2 = 2131296260;
			
			// aapt resource value: 0x7f09000e
			public const int textView1 = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int textView2 = 2131296271;
			
			// aapt resource value: 0x7f090011
			public const int textView3 = 2131296273;
			
			// aapt resource value: 0x7f090018
			public const int textView4 = 2131296280;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ClientActivity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ConnectingDialog = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ConnectManuallyDialog = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ContactItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ContactListActivity = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ScannerOverlay = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ServerConnectedActivity = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int TransferListCompletedItem = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int TransferListItem = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int zxingscanneractivitylayout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int zxingscannerfragmentlayout = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int ContactListMenu = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f06000f
			public const int Abort = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int AbortAll = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int AbortAreYouSure = 2131099665;
			
			// aapt resource value: 0x7f060000
			public const int ApplicationName = 2131099648;
			
			// aapt resource value: 0x7f060015
			public const int Cancel = 2131099669;
			
			// aapt resource value: 0x7f06000c
			public const int ClientSendContacts = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int ClientSendFile = 2131099659;
			
			// aapt resource value: 0x7f060021
			public const int ConnectManuallyInfo = 2131099681;
			
			// aapt resource value: 0x7f06000a
			public const int ConnectedToFormatStr = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int Connecting = 2131099657;
			
			// aapt resource value: 0x7f06001a
			public const int ContactFormatStr = 2131099674;
			
			// aapt resource value: 0x7f06000e
			public const int CurrentFileTransferRemainingFormatStr = 2131099662;
			
			// aapt resource value: 0x7f060008
			public const int Disconnect = 2131099656;
			
			// aapt resource value: 0x7f060024
			public const int ErrEstablishServer = 2131099684;
			
			// aapt resource value: 0x7f060022
			public const int IPAddress = 2131099682;
			
			// aapt resource value: 0x7f06000d
			public const int IncomingFileTransfers = 2131099661;
			
			// aapt resource value: 0x7f060013
			public const int No = 2131099667;
			
			// aapt resource value: 0x7f060019
			public const int NoWifiInfo = 2131099673;
			
			// aapt resource value: 0x7f060014
			public const int OK = 2131099668;
			
			// aapt resource value: 0x7f060018
			public const int OpenWifiSettings = 2131099672;
			
			// aapt resource value: 0x7f060023
			public const int Password = 2131099683;
			
			// aapt resource value: 0x7f06001f
			public const int PleaseWaitForServerToInitialize = 2131099679;
			
			// aapt resource value: 0x7f060005
			public const int QRCodeInvalid = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int QRCodeInvalidTitle = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int ReceiveFiles = 2131099654;
			
			// aapt resource value: 0x7f06001c
			public const int ReceivingCapitals = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int ReceivingInfo = 2131099677;
			
			// aapt resource value: 0x7f060017
			public const int Retry = 2131099671;
			
			// aapt resource value: 0x7f06001e
			public const int ScanCode = 2131099678;
			
			// aapt resource value: 0x7f060020
			public const int ScannerOverlayPleaseScan = 2131099680;
			
			// aapt resource value: 0x7f060016
			public const int Send = 2131099670;
			
			// aapt resource value: 0x7f060007
			public const int SendFiles = 2131099655;
			
			// aapt resource value: 0x7f06001b
			public const int SendingCapitals = 2131099675;
			
			// aapt resource value: 0x7f060002
			public const int ServerConnectManually = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int ServerConnectManuallyInfoFormatStr = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int ServerQRCodeInformation = 2131099649;
			
			// aapt resource value: 0x7f060012
			public const int Yes = 2131099666;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070002
			public const int main_layout = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int menu_text = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int plain_button = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int scanner_overlay_text = 2131165187;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
