#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SecureFileTransfer.Resource", IsApplication=true)]

namespace SecureFileTransfer
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::SecureFileTransfer.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::SecureFileTransfer.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::SecureFileTransfer.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040004
			public const int plain_button_background = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int plain_button_background_normal = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int plain_button_background_pressed = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int text_color = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int text_shadow_color = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bkg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000a
			public const int AbortButton = 2131230730;
			
			// aapt resource value: 0x7f08000c
			public const int CheckBox = 2131230732;
			
			// aapt resource value: 0x7f080015
			public const int ConnectManuallyButton = 2131230741;
			
			// aapt resource value: 0x7f080000
			public const int ConnectedToField = 2131230720;
			
			// aapt resource value: 0x7f08000e
			public const int ContactName = 2131230734;
			
			// aapt resource value: 0x7f08000d
			public const int ContactPhoto = 2131230733;
			
			// aapt resource value: 0x7f080007
			public const int CurrentTransferFileNameField = 2131230727;
			
			// aapt resource value: 0x7f080005
			public const int CurrentTransferLayout = 2131230725;
			
			// aapt resource value: 0x7f080008
			public const int CurrentTransferProgressBar = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int CurrentTransferStatus = 2131230729;
			
			// aapt resource value: 0x7f080006
			public const int CurrentTransferTitleLabel = 2131230726;
			
			// aapt resource value: 0x7f08000b
			public const int DisconnectButton = 2131230731;
			
			// aapt resource value: 0x7f08001a
			public const int FileNameLabel = 2131230746;
			
			// aapt resource value: 0x7f08000f
			public const int ListView = 2131230735;
			
			// aapt resource value: 0x7f08001b
			public const int ProgressBar = 2131230747;
			
			// aapt resource value: 0x7f080017
			public const int QRContainer = 2131230743;
			
			// aapt resource value: 0x7f080014
			public const int QRContainerView = 2131230740;
			
			// aapt resource value: 0x7f080011
			public const int ScanCodeButton = 2131230737;
			
			// aapt resource value: 0x7f08001e
			public const int Send = 2131230750;
			
			// aapt resource value: 0x7f080002
			public const int SendContactsButton = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int SendPicturesButton = 2131230721;
			
			// aapt resource value: 0x7f08001c
			public const int StatusLabel = 2131230748;
			
			// aapt resource value: 0x7f080018
			public const int TransfersListView = 2131230744;
			
			// aapt resource value: 0x7f08001d
			public const int contentFrame = 2131230749;
			
			// aapt resource value: 0x7f080019
			public const int imageView1 = 2131230745;
			
			// aapt resource value: 0x7f080003
			public const int linearLayout1 = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int linearLayout2 = 2131230724;
			
			// aapt resource value: 0x7f080016
			public const int textView1 = 2131230742;
			
			// aapt resource value: 0x7f080010
			public const int textView2 = 2131230736;
			
			// aapt resource value: 0x7f080012
			public const int textView3 = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int textView4 = 2131230739;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ClientActivity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ContactItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ContactListActivity = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ServerActivity = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ServerConnectedActivity = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int TransferListCompletedItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int TransferListItem = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int zxingscanneractivitylayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int zxingscannerfragmentlayout = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int ContactListMenu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f05000f
			public const int Abort = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int AbortAll = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int AbortAreYouSure = 2131034129;
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int ClientSendContacts = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int ClientSendFile = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int ConnectedToFormatStr = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int Connecting = 2131034121;
			
			// aapt resource value: 0x7f050015
			public const int ContactFormatStr = 2131034133;
			
			// aapt resource value: 0x7f05000e
			public const int CurrentFileTransferRemainingFormatStr = 2131034126;
			
			// aapt resource value: 0x7f050008
			public const int Disconnect = 2131034120;
			
			// aapt resource value: 0x7f05000d
			public const int IncomingFileTransfers = 2131034125;
			
			// aapt resource value: 0x7f050013
			public const int No = 2131034131;
			
			// aapt resource value: 0x7f05001a
			public const int PleaseWaitForServerToInitialize = 2131034138;
			
			// aapt resource value: 0x7f050005
			public const int QRCodeInvalid = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int QRCodeInvalidTitle = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int ReceiveFiles = 2131034118;
			
			// aapt resource value: 0x7f050017
			public const int ReceivingCapitals = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int ReceivingInfo = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int ScanCode = 2131034137;
			
			// aapt resource value: 0x7f050014
			public const int Send = 2131034132;
			
			// aapt resource value: 0x7f050007
			public const int SendFiles = 2131034119;
			
			// aapt resource value: 0x7f050016
			public const int SendingCapitals = 2131034134;
			
			// aapt resource value: 0x7f050002
			public const int ServerConnectManually = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int ServerConnectManuallyInfoFormatStr = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int ServerQRCodeInformation = 2131034113;
			
			// aapt resource value: 0x7f050012
			public const int Yes = 2131034130;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060002
			public const int main_layout = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int menu_text = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int plain_button = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
